/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author user
 */
public class doctortopatient extends javax.swing.JFrame {

    /**
     * Creates new form doctortopatient
     */
    public doctortopatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        surgery = new javax.swing.JButton();
        treatment = new javax.swing.JButton();
        labresult = new javax.swing.JButton();
        radiology = new javax.swing.JButton();
        perscription = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("HealthTracker");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(966, 6, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 36), new java.awt.Color(0, 51, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        surgery.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        surgery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/surgeryyy.jpg"))); // NOI18N
        surgery.setText("Manage Surgeries");
        surgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surgeryActionPerformed(evt);
            }
        });
        jPanel1.add(surgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 116, -1, -1));

        treatment.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        treatment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/treatmengtt.jpg"))); // NOI18N
        treatment.setText("Treatment");
        treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treatmentActionPerformed(evt);
            }
        });
        jPanel1.add(treatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 117, 314, 136));

        labresult.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/labbb.jpg"))); // NOI18N
        labresult.setText("Lab Test Results");
        labresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labresultActionPerformed(evt);
            }
        });
        jPanel1.add(labresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 283, -1, -1));

        radiology.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        radiology.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/radiologyyy.jpg"))); // NOI18N
        radiology.setText("Radiology");
        radiology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiologyActionPerformed(evt);
            }
        });
        jPanel1.add(radiology, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 283, 297, 139));

        perscription.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        perscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/perscrip.jpg"))); // NOI18N
        perscription.setText("Prescriptions");
        perscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perscriptionActionPerformed(evt);
            }
        });
        jPanel1.add(perscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 116, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 44, 1130, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 493, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/741800-safeimagekit.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -2, 1160, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void surgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surgeryActionPerformed
        DoctorSurgery msurgeries = new DoctorSurgery();
        msurgeries.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_surgeryActionPerformed

    private void treatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treatmentActionPerformed
        // TODO add your handling code here:
        DoctorTreatment treatments = new DoctorTreatment();
        treatments.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_treatmentActionPerformed

    private void labresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labresultActionPerformed
        // TODO add your handling code here:
        DoctorLabResults labresults = new DoctorLabResults();
        labresults.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labresultActionPerformed

    private void radiologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiologyActionPerformed
        // TODO add your handling code here:
        DoctorRadiology radiology = new DoctorRadiology();
        radiology.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_radiologyActionPerformed

    private void perscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perscriptionActionPerformed
        // TODO add your handling code here:
        DoctorPrescrip pe = new DoctorPrescrip();
        pe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perscriptionActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        doctor_homepage dochome = new doctor_homepage();
        dochome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctortopatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctortopatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctortopatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctortopatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctortopatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton labresult;
    private javax.swing.JButton perscription;
    private javax.swing.JButton radiology;
    private javax.swing.JButton surgery;
    private javax.swing.JButton treatment;
    // End of variables declaration//GEN-END:variables
}
